apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      name: metadata-service
      labels:
        app: node-app
    spec:
      containers:
        - name: metadata-service
          image: vraravam/metadata-service:1.0.2
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 3
          envFrom:
            - configMapRef:
                name: metadata-service-config-map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-service-config-map
data:
  MONGO_URL: mongodb://service-for-standalone-mongo/metadata
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-service
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
