apiVersion: v1
kind: Pod
metadata:
  name: metadata-service
  labels:
    name: metadata-service
spec:
  volumes:
    - name: html-docs
      emptyDir: {}
  containers:
    - name: metadata-service
      image: vraravam/metadata-service:1.0.0
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: html-docs
          mountPath: /location1
    - name: vijay-service
      image: vraravam/metadata-service:1.0.0
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: html-docs
          mountPath: /location2

# Run the file using these commands:
# kubectl create -f single-container.kube.yaml
# kubectl get all -o wide
# Verify that the pod is running, get its IP address
# minikube ssh
# curl http://<IP>:8080/actuator/info
# kubectl port-forward metadata-service 8081:8080
# Open in browser: http://localhost:8081/actuator/info
