apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: standalone-mongo-for-metadata-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standalone-mongo-for-metadata-service
  template:
    metadata:
      name: standalone-mongo-for-metadata-service
      labels:
        app: standalone-mongo-for-metadata-service
    spec:
      containers:
        - name: standalone-mongo-for-metadata-service
          image: vraravam/mongo:1.0
          ports:
            - containerPort: 27017
