apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: metadata-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      name: metadata-service
      labels:
        app: node-app
    spec:
      containers:
        - name: metadata-service
          image: vraravam/metadata-service:1.0.1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 3
