apiVersion: v1
kind: Service
metadata:
  name: service-for-standalone-mongo
spec:
  selector:
    app: standalone-mongo-for-metadata-service
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
