apiVersion: apps/v1
kind: Deployment
metadata:
  name: standalone-mongo-for-metadata-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standalone-mongo-for-metadata-service
  template:
    metadata:
      name: standalone-mongo-for-metadata-service
      labels:
        app: standalone-mongo-for-metadata-service
    spec:
      containers:
        - name: standalone-mongo-for-metadata-service
          image: vraravam/mongo:1.0
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: service-for-standalone-mongo
spec:
  selector:
    app: standalone-mongo-for-metadata-service
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
